### PR TITLE
fix component(filename) add separator between filename and icons

### LINKED ISSUE #794: Filename component: symbols space
So hey........... .-.

The default vim statusline adds one space between the filename and the first symbol

default: `file.xyz [+][RO]`
lualine:  `file.xyz[+][RO]`

### PR DESCRIPTION
**Pull request by zappolowski**
This makes it behave like the default statusline by have a space between the filename and the following icons (but not between the icons).

While at it, also added new test case to ensure that representation is correct, when both states (modified and readonly) are active at the same time.

fixes #794

### CODE REVIEW

File: lua/lualine/components/filename.lua [hunk 1]
```diff
@@ -80,19 +80,21 @@ M.update_status = function(self)
...
     end
   end
 
   if self.options.newfile_status and is_new_file() then
-    data = data .. self.options.symbols.newfile
+    table.insert(symbols, self.options.symbols.newfile)
   end
-  return data
+
+  return data .. (#symbols > 0 and ' ' .. vim.fn.join(symbols, '') or '')
```
Comment (shadmansaleh) [inline lua/lualine/components/filename.lua:97]: Use `table.concat(symbols)` instead of `vim.fn.join`. That way we won't have type conversion back and forth.

Otherwise looks good to me

**Comment by zappolowski** [comment]
One idea came up: should we make the separator configurable?

**Comment by shadmansaleh** [comment]
> One idea came up: should we make the separator configurable?

Doesn't seem very useful to be honest. Lets leave it for now.
