### PR TITLE
fix component(filetype) proper icon based on filetype

### LINKED ISSUE #578: Bug: lualine doesn't show filetype icon for files without extension
The 'filetype' component doesn't find the filetype icon sometimes:

_HOME_src_gdk_gitlab_a_rb

<details>
<summary>My config</summary>

```lua
lualine.setup({
  extensions = {
    require('plugins.statusline.extensions.filetree'),
    require('plugins.statusline.extensions.neoterm'),
  },
  options = {
    theme = theme.colorscheme,
    icons_enabled = true,
    section_separators = '',
    component_separators = '',
  },
  sections = {
    lualine_a = { utils.bufnr() },
    lualine_b = {
      {
        'filetype',
        colored = true,
        icon_only = true,
        padding = 1,
      },
      {
        'filename',
        file_status = true,
        path = 1,
        shorting_target = 30,
        symbols = { modified = ' ', readonly = ' ', unnamed = ' [No Name] ' },
        padding = 0,
      },
    },
    lualine_c = {
      { vim.my.treesitter.gps.location },
    },
    lualine_x = {
      {
        'diagnostics',
        sources = { 'nvim_diagnostic' },
        symbols = {
          error = theme.signs.error,
          warn = theme.signs.warn,
          hint = theme.signs.hint,
          info = theme.signs.info,
        },
        color_error = theme.colors.error,
        color_warn = theme.colors.warn,
        color_hint = theme.colors.hint,
        color_info = theme.colors.info,
      },
    },
    lualine_y = { 'diff' },
    lualine_z = {
      { '[[%3l:%-3c]]' },
      utils.mode(),
    },
  },
  inactive_sections = {
    lualine_a = { utils.bufnr() },
    lualine_b = utils.filename({ icon_color = false }),
    lualine_c = {},
    lualine_x = {},
    lualine_y = {},
    lualine_z = {},
  },
})
```

</details>

### Self Checks

- [x] I'm using the latest lualine.
- [x] I didn't find the issue in exsisting issues or prs.

### How to reproduce the problem

I'm not sure, but it seems related to how the filetype is set, when it's set in `ftdetect` with `BufReadPos` it doesn't set the icon.

### Minimal config to reproduce the issue

<details>
<summary>Config</summary>

</details>

### PR DESCRIPTION
**Pull request by zappolowski**
With https://github.com/kyazdani42/nvim-web-devicons/pull/125 a filetype based lookup was implemented upstream which can be used to get an icon when a file doesn't have an extension.

fixes #578

### CODE REVIEW

**Comment by shadmansaleh** [comment]
That's a good news. Thanks for the pr.

File: tests/spec/component_spec.lua [hunk 1]
```diff
@@ -258,14 +258,21 @@ end)
 
 describe('Filetype component', function()
   local filetype
+  local orig_expand
 
   before_each(function()
     filetype = vim.bo.filetype
     vim.bo.filetype = 'lua'
+    orig_expand = vim.fn.expand
+    vim.fn.expand = function(fmt)
```
Comment (shadmansaleh) [inline tests/spec/component_spec.lua:267]: You can use `stubs` from testing framework instead of overwriting the function yourself. There are examples in the test suit and you can take a look at the lua busted docs for more info.

File: lua/lualine/components/filetype.lua [hunk 2]
```diff
@@ -31,9 +31,12 @@ function M:apply_icon()
   local icon, icon_highlight_group
   local ok, devicons = pcall(require, 'nvim-web-devicons')
   if ok then
-    local f_name, f_extension = vim.fn.expand('%:t'), vim.fn.expand('%:e')
-    f_extension = f_extension ~= '' and f_extension or vim.bo.filetype
-    icon, icon_highlight_group = devicons.get_icon(f_name, f_extension)
```
Comment (shadmansaleh) [inline lua/lualine/components/filetype.lua:36]: Do we need to remove these ? Can't we use get_icon_by_filetype when get_icon returns nil as fallback?

File: tests/spec/component_spec.lua (hunk 1 above)
Comment (zappolowski) [reply tests/spec/component_spec.lua:267]: While at it shall I use `stub` for accessing `nvim-web-devicons` as well? If yes, should I put it on another (refactoring) PR to focus on file type icons in this one?

File: lua/lualine/components/filetype.lua (hunk 2 above)
Comment (zappolowski) [reply lua/lualine/components/filetype.lua:36]: This might work ... playing around with `get_icon` this might be a valid simplifcation:
```lua
icon, icon_highlight_group = devicons.get_icon(vim.fn.expand('%:t'))
if icon == nil then
  icon, icon_highlight_group = devicons.get_icon_by_filetype(vim.bo.filetype)
end
```
as `get_icon` determines the extension from the name if no extension (2nd argument) is given.

File: tests/spec/component_spec.lua (hunk 1 above)
Comment (shadmansaleh) [reply tests/spec/component_spec.lua:267]: Sure if you feel like it you can do that too.

File: lua/lualine/components/filetype.lua (hunk 2 above)
Comment (shadmansaleh) [reply lua/lualine/components/filetype.lua:36]: That looks cleaner . You can change it to this.

I was thinking about keeping the older filetype based check because the webdeviconcs pr stated the list added wasn't exhaustive . But now looking at it I think in the cases where older filetype check would matter ar already supported by `get_icon_by_filetype` . So we can remove that.

**Comment by shadmansaleh** [comment]
I don't exactly remember was there something blocking it's merge ? where were we ? Does this version work properly ?

**Comment by zappolowski** [comment]
I've kept the branch up to date and tests are still passing. As far as I can tell, the discussions are resolved.
